#!/bin/bash
generate_random_string() {
    local length=$1
    local chars=${2:-"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+-="}
    local random_string=""

    if [ -z "$length" ]; then
        echo "❌ Ошибка: Не указана длина строки."
        return 1
    fi

    for ((i = 0; i < length; i++)); do
        random_string+="${chars:RANDOM%${#chars}:1}"
    done
    echo "$random_string"
}

register_panel_user_interactive() {
    # 1. Запрашиваем домен панели
    read -p "Пожалуйста, введите домен вашей панели (например, panel.example.com): " domain
    if [ -z "$domain" ]; then
        echo "❌ ОШИБКА: Домен не может быть пустым."
        sleep 3
        return 1
    fi

    # 2. Генерируем случайные логин и пароль
    local username=$(generate_random_string 12)
    local password=$(generate_random_string 24)
    
    echo "📝 Генерирую случайные учетные данные..."
    sleep 2
    
    # 3. Отправляем API-запрос на регистрацию
    local api_url="https://$domain/api/auth/register"
    local json_data="{\"username\": \"$username\", \"password\": \"$password\"}"
    
    local response=$(curl -s -X POST "$api_url" \
                     -H "Content-Type: application/json" \
                     -d "$json_data")

    # 4. Проверяем ответ от сервера на наличие токена
    local token=$(echo "$response" | jq -r '.response.token' 2>/dev/null)
    
    if [ -n "$token" ]; then
        echo "🎉 УСПЕХ: Автоматическая регистрация завершена!"
        
        # 5. Сохраняем учетные данные и токен в файл .env в папке скрипта
        local SCRIPT_DIR="/opt/Remnawave-autoinstall-script"
        local ENV_FILE="$SCRIPT_DIR/.env"
        
        echo -e "\n# Generated by script on $(date)" >> "$ENV_FILE"
        echo "ADMIN_USERNAME=$username" >> "$ENV_FILE"
        echo "ADMIN_PASSWORD=$password" >> "$ENV_FILE"
        echo "JWT_API_TOKENS_SECRET=$token" >> "$ENV_FILE"
        
        echo "✅ Учетные данные и токен сохранены в $ENV_FILE"
        
        # 6. Выводим данные для пользователя
        echo "❗❗ ВНИМАНИЕ: СОХРАНИТЕ ЭТИ ДАННЫЕ. ОНИ НЕ БУДУТ ПОКАЗАНЫ СНОВА."
        echo "🔑 Логин: $username"
        echo "🔑 Пароль: $password"
        
        sleep 10
        return 0
    else
        echo "❌ ОШИБКА: Не удалось зарегистрировать пользователя."
        echo "❗ Ответ сервера: $response"
        sleep 5
        return 1
    fi
}
