#!/bin/bash
generate_random_string() {
    local length=$1
    local chars=${2:-"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+-="}
    local random_string=""

    if [ -z "$length" ]; then
        echo "$(get_text "API_ERROR_NO_LENGTH")"
        return 1
    fi

    for ((i = 0; i < length; i++)); do
        random_string+="${chars:RANDOM%${#chars}:1}"
    done
    echo "$random_string"
}

register_panel_user_interactive() {
    # 1. Запрашиваем домен панели
    read -p "$(get_text "API_REG_PROMPT_DOMAIN")" domain
    if [ -z "$domain" ]; then
        echo "$(get_text "API_ERROR_DOMAIN_EMPTY")"
        sleep 3
        return 1
    fi

    # 2. Генерируем случайные логин и пароль
    local username=$(generate_random_string 12)
    local password=$(generate_random_string 24)
    
    echo "$(get_text "API_REG_GENERATING_CREDS")"
    sleep 2
    
    # 3. Отправляем API-запрос на регистрацию
    local api_url="https://$domain/api/auth/register"
    local json_data="{\"username\": \"$username\", \"password\": \"$password\"}"
    
    local response=$(curl -s -X POST "$api_url" \
                     -H "Content-Type: application/json" \
                     -d "$json_data")

    # 4. Проверяем ответ от сервера на наличие токена
    local token=$(echo "$response" | jq -r '.response.token' 2>/dev/null)
    
    if [ -n "$token" ]; then
        echo "$(get_text "API_REG_SUCCESS")"
        
        # 5. Сохраняем учетные данные и токен в файл .env в папке скрипта
        local SCRIPT_DIR="/opt/Remnawave-autoinstall-script"
        local ENV_FILE="$SCRIPT_DIR/.env"
        
        echo -e "\n# Generated by script on $(date)" >> "$ENV_FILE"
        echo "ADMIN_USERNAME=$username" >> "$ENV_FILE"
        echo "ADMIN_PASSWORD=$password" >> "$ENV_FILE"
        echo "JWT_API_TOKENS_SECRET=$token" >> "$ENV_FILE"
        
        echo "$(get_text "API_REG_CREDS_SAVED")$ENV_FILE"
        
        # 6. Выводим данные для пользователя
        echo "$(get_text "API_REG_SAVE_WARNING")"
        echo "$(get_text "API_REG_LOGIN")$username"
        echo "$(get_text "API_REG_PASSWORD")$password"
        
        sleep 10
        return 0
    else
        echo "$(get_text "API_REG_FAILED")"
        echo "$(get_text "API_REG_SERVER_RESPONSE")$response"
        sleep 5
        return 1
    fi
}